export const companies = [
  { id: 1, name: "Amazon", image: "/companies/amazon.svg" },
  { id: 2, name: "Adobe", image: "/companies/adobe.svg" },
  { id: 3, name: "BBC", image: "/companies/bbc.svg" },
  {
    id: 4,
    name: "ICAI",
    image: "/companies/the-institute-of-chartered-accountants-of-india.svg",
  },
  { id: 5, name: "Oracle", image: "/companies/oracle.svg" },
  { id: 6, name: "EY", image: "/companies/EY.svg" },
  { id: 7, name: "Dell", image: "/companies/dell.svg" },
  { id: 8, name: "KMPG", image: "/companies/kpmg.svg" },
  { id: 9, name: "ISD", image: "/companies/ISD.svg" },
  { id: 10, name: "Kingfisher", image: "/companies/kingfisher.svg" },
  { id: 11, name: "NDTV", image: "/companies/ndtv.svg" },
  { id: 12, name: "nestle", image: "/companies/nestle.svg" },
  { id: 13, name: "Google", image: "/companies/google.svg" },
  { id: 14, name: "Xebia", image: "/companies/xebia.svg" },
  { id: 15, name: "xenith", image: "/companies/xenith.svg" },
  { id: 16, name: "Buyjs", image: "/companies/buyjs.svg" },
  { id: 17, name: "Meta", image: "/companies/meta.svg" },
  { id: 18, name: "Arena", image: "/companies/arena.svg" },
  { id: 19, name: "Canopius", image: "/companies/canopius.svg" },
  { id: 20, name: "Logic window", image: "/companies/Logic-window.svg" },
  { id: 21, name: "IIT Kanpur", image: "/companies/iit-kanpur.svg" },
  { id: 22, name: "Tcs", image: "/companies/tcs.svg" },
  { id: 23, name: "Vahan", image: "/companies/vahan.svg" },
  { id: 24, name: "Tango", image: "/companies/tango.svg" },
  { id: 25, name: "Axis Bank", image: "/companies/AXISBANK.svg" },
  { id: 26, name: "Ved World", image: "/companies/ved-world.svg" },
  { id: 27, name: "BPL", image: "/companies/bpl.svg" },
  { id: 28, name: "ISB", image: "/companies/isb.svg" },

  {
    id: 30,
    name: "Aditya Birla Group",
    image: "/companies/Aditya-Birla-Group.svg",
  },
  {
    id: 31,
    name: "next-leap",
    image: "/companies/next-leap.avif",
  },
  {
    id: 32,
    name: "World Food Programme",
    image: "/companies/World_Food_Programme.svg",
  },
  {
    id: 33,
    name: "Secure Sleuths",
    image: "/companies/Secure-Sleuths.jpg",
  },
  {
    id: 34,
    name: "Deloitte",
    image: "/companies/deloitte.svg",
  },
  {
    id: 35,
    name: "ICICI Bank",
    image: "/companies/ICICI-Bank.png",
  },
  {
    id: 36,
    name: "Logical AI",
    image: "/companies/logical-ai.jpg",
  },
  {
    id: 37,
    name: "M4U Media",
    image: "/companies/m4u-media.png",
  },

  // Add all your company data here
];

export const people = [
  {
    id: 1,
    name: "Dr. Ashwin Naayaak",
    companyId: [1, 26],
    image: "/people/Dr-Ashwin-Naayaak.svg",
  },
  {
    id: 4,
    name: "Prof Sukumar Rangachari",
    companyId: [6, 21, 27, 28],
    image: "/people/Prof-Sukumar-Rangachari.svg",
  },
  {
    id: 5,
    name: "Anurag Rao",
    companyId: 5,
    image: "/people/Anurag-Rao.svg",
  },
  {
    id: 6,
    name: "Ritu Bararia",
    companyId: 10,
    image: "/people/Ritu-Bararia.svg",
  },
  {
    id: 7,
    name: "Aditya Jain",
    companyId: 8,
    image: "/people/Aditya-Jain.svg",
  },
  {
    id: 8,
    name: "Panchi Samuthirakani",
    companyId: 8,
    image: "/people/Panchi-Samuthirakani.svg",
  },
  {
    id: 11,
    name: "Rtn Lakshmi Balaji",
    companyId: [4, 21],
    image: "/people/Rtn-Lakshmi-Balaji.svg",
  },
  {
    id: 12,
    name: "Bhushan Sao",
    companyId: 12,
    image: "/people/Bhushan-Sao.svg",
  },
  {
    id: 14,
    name: "Gaurav Pandey",
    companyId: 14,
    image: "/people/Gaurav-Pandey.svg",
  },
  {
    id: 15,
    name: "Sandesh Ramachandra",
    companyId: [5, 28],
    image: "/people/Sandesh-Ramachandra.svg",
  },
  {
    id: 16,
    name: "Swaroop Pai",
    companyId: 5,
    image: "/people/Swaroop-Pai.svg",
  },
  {
    id: 17,
    name: "Seshadri Ayengar",
    companyId: 17,
    image: "/people/Shesh.svg",
  },
  {
    id: 20,
    name: "Shaheen Sharma",
    companyId: 20,
    image: "/people/Shaheen-Sharma.svg",
  },
  {
    id: 21,
    name: "Jaideep Singh Gaur",
    companyId: 8,
    image: "/people/Jaideep-Singh-Gaur.svg",
  },
  {
    id: 22,
    name: "Dnyanada Kulkarni",
    companyId: 25,
    image: "/people/Dnyanada-Kulkarni.svg",
  },
  {
    id: 24,
    name: "Jisa Mathew",
    companyId: 2,
    image: "/people/Jisa-Mathew.svg",
  },
  {
    id: 25,
    name: "Anindita Chatterjee",
    companyId: 25,
    image: "/people/Anindita-Chatterjee.svg",
  },
  {
    id: 28,
    name: "Ankur Mehra",
    companyId: 17,
    image: "/people/Ankur-Mehra.svg",
  },
  {
    id: 29,
    name: "Meghna Suresh",
    companyId: 11,
    image: "/people/Meghna-Suresh.svg",
  },
  {
    id: 30,
    name: "Antara Kumar",
    companyId: 30,
    image: "/people/Antara-Kumar.svg",
  },
  {
    id: 33,
    name: "Vinay Jalla",
    companyId: 3,
    image: "/people/Vinay-Jalla.svg",
  },
  {
    id: 34,
    name: "Nandish Yadav",
    companyId: 16,
    image: "/people/Nandish-Yadav.svg",
  },
  {
    id: 36,
    name: "Snehal Badodkar",
    companyId: 24,
    image: "/people/Snehal-Badodkar.svg",
  },
  {
    id: 37,
    name: "Srinath R",
    companyId: 37,
    image: "/people/Srinath.svg",
  },
  {
    id: 39,
    name: "Rahul Kumawat",
    companyId: 23,
    image: "/people/Rahul-Kumawat.svg",
  },
  {
    id: 41,
    name: "Gaurav Suri",
    companyId: [4, 21, 28],
    image: "/people/Gaurav-Suri.svg",
  },
  {
    id: 44,
    name: "Suresh Dinakaran",
    companyId: 9,
    image: "/people/Suresh-Dinakaran.svg",
  },
  {
    id: 46,
    name: "Jitendra S Joshi",
    companyId: 36,
    image: "/people/Jitendra S Joshi.svg",
  },
  {
    id: 47,
    name: "RItuja Patil",
    companyId: 45,
    image: "/people/RItuja-Patil.svg",
  },
  {
    id: 49,
    name: "Ajoy Velunny",
    companyId: 13,
    image: "/people/Ajoy-Velunny.svg",
  },
  {
    id: 50,
    name: "Dr Sanyukta Kashalkar",
    companyId: 45,
    image: "/people/Dr-Sanyukta-Kashalkar-Karve.svg",
  },
  {
    id: 51,
    name: "Ankit Singh Rathore",
    companyId: 30,
    image: "/people/Ankit-Singh-Rathore.svg",
  },
  {
    id: 52,
    name: "Rituparna Baritha",
    companyId: 1,
    image: "/people/Rituparna-Baritha.svg",
  },
  {
    id: 53,
    name: "Abhiram Babu Kandoor",
    companyId: 35,
    image: "/people/Abhiram-babu.svg",
  },
  {
    id: 54,
    name: "Aditya Kartik",
    companyId: [1, 6],
    image: "/people/Aditya-Kartik.svg",
  },
  {
    id: 57,
    name: "Anunya Srivasthva",
    companyId: 16,
    image: "/people/Anunya-Srivasthva.svg",
  },
  {
    id: 61,
    name: "Rahul",
    companyId: [21, 23],
    image: "/people/rahul.svg",
  },
  {
    id: 64,
    name: "Anurag Singh",
    companyId: 7,
    image: "/people/Anurag-Singh.svg",
  },
];
